#!/bin/bash
# -*- bash -*-

# This gives you access to the custom DSL
. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/defaults.conf"

# Get CI_USER
if [ -z "${TRAVIS}" ]; then
  CI_USER="vagrant"
else
  CI_USER="${USER}"
fi

# Install a specific version of Ansible
# install_ansible ${test_ansible_version}
printf "[defaults]\nhostfile = %s\nroles_path = %s\n" \
  "${ROLESPEC_HOSTS}" \
  "${ROLESPEC_ANSIBLE_ROLES}" \
  > "${ROLESPEC_ANSIBLE_CONFIG}"

ansible --version
echo

# Auto resolve dependencies
if [[ -f "${ROLESPEC_META}" && -n "${ROLESPEC_TRAVIS}" ]]; then
  # Space separated list of unique dependencies in Galaxy format
  local dependencies="$(grep "\- role: " "${ROLESPEC_META}" | sed -e "s/^[ \t]*//" \
    | awk '{print $3}' | uniq | tr '\n' ' ')"

  if [[ -n "${dependencies}" ]]; then
    echo
    rolespec_run "Galaxy install role dependencies"
    ansible-galaxy install -f ${dependencies}
  fi
fi

# Préreq
ansible-galaxy install -r requirements.yml

# Check syntax first, and then that the playbook runs
assert_playbook_runs -e "ci_user=$CI_USER" -vvvv

# Check that the playbook is idempotent
assert_playbook_idempotent -e "ci_user=$CI_USER" 
